### ISSUE TITLE
能不能考虑加个全局开关

### ISSUE THREAD

**Issue by MUGIW** [TWT233/GBFRAuto#2]
窗口挂机的时候看视频之类的有时候要切出去需要暂停脚本，这时候基本只能用“[”强制退出，是不是可以增加两个按键做整个脚本得开关控制，以及增加一个GBFR窗口的active的循环检测实现切出程序自动暂停脚本和切回程序自动恢复脚本运行，谢谢老哥

**Comment by TWT233** [comment]
我看看autohotkey有没有全局开关的能力，没有的话的有点难做

**Comment by blangero** [comment]
how about using a key to reset all selections?

**Comment by MUGIW** [comment]
> 我看看autohotkey有没有全局开关的能力，没有的话的有点难做

以前玩别的游戏拿AHK写简单脚本的时候就是global一个bool变量，通过指定按键更改bool变量值，然后所有循环和触发都判断下这个bool变量

**Comment by TWT233** [comment]
Not only selections but all current running conditions/km

I found a ask builtin function `Reload()` seem works, will try after

(Or you can give it a try if willing to


On Feb 27, 2024, at 12:50, Blangero Wang ***@***.***> wrote:



how about using a key to reset all selections?

**Comment by TWT233** [comment]
看了下内置有个重置脚本的函数，我晚上试试看

On Feb 27, 2024, at 13:17, MUGIW ***@***.***> wrote:



我看看autohotkey有没有全局开关的能力，没有的话的有点难做

以前玩别的游戏拿AHK写简单脚本的时候就是global一个bool变量，通过指定按键更改bool变量值，然后所有循环和触发都判断下这个bool变量

**Comment by TWT233** [comment]
done in 240227.2023
